on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    tags:
      - '*'


jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
           docker build . --file Dockerfile --tag mdb770/api:$IMAGE_TAG
           docker push mdb770/api:$IMAGE_TAG
