on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    tags:
      - '*'


jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - uses: actions/checkout@v3
    - name: Extract Git Tag
      run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: print value  
      run: echo $GITHUB_ENV
    - name: Build the Docker image
      run: docker build  --file Dockerfile --tag mdb770/api:$IMAGE_TAG .
    - name: Docker Push
      run: docker push mdb770/api:$IMAGE_TAG
