name: Docker Image CI

on:
  push:
    branches: [ master ]
    
env:
  IMAGE_TAG: ${{ github.sha }}
     
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - uses: actions/checkout@v3
    - name: Build and push to Dockehub
      run: |
           docker build . --file Dockerfile --tag mdb770/api:$IMAGE_TAG
           docker push mdb770/api:$IMAGE_TAG
    - name: deploy to cluster
      uses: ghostzero/kubectl@v1
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        
      with:
        args: set image --record deployment/api api=mdb770/api:$IMAGE_TAG
